export const travelTipsCategories = [
  {
    id: "1",
    title: "Water Sports",
    imageUrl: "https://images.unsplash.com/photo-1662443651821-8b995efd665f",
    emoji: "🌊",
    tips: [
      "🦺 **Always wear a life jacket**, even if you’re a good swimmer.",
      "💧 **Stay hydrated under the sun** – bring water and drink frequently.",
      "🌤️ **Check the weather conditions** before going out on the water, especially for storms or high winds.",
      "🏊 **Practice safety techniques** like treading water or swimming with a buddy.",
      "🚤 **Learn the basics of handling watercraft** (jet skis, boats) before hitting the water.",
      "🐚 **Know your limits** and don’t push yourself too hard in the water.",
      "🧴 **Apply sunscreen regularly** to prevent sunburn during water activities.",
      "🔦 **Have a waterproof flashlight** if you plan to be out near dusk or night.",
    ],
  },
  {
    id: "2",
    title: "Outdoor Adventures",
    imageUrl: "https://images.unsplash.com/photo-1465188035480-cf3a60801ea5?q=80&w=580&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    emoji: "👟",
    tips: [
      "🥾 **Wear sturdy, comfortable footwear** suitable for hiking or walking on rough terrain.",
      "💦 **Pack enough water and snacks** to keep your energy up during long treks.",
      "🗺️ **Bring a map or GPS device** to avoid getting lost in unfamiliar areas.",
      "🦝 **Be mindful of wildlife** – keep a safe distance from animals and respect their space.",
      "🌳 **Leave no trace**: Clean up after yourself and respect nature, leaving it as you found it.",
      "⚖️ **Balance your pack weight** to avoid straining your body and causing discomfort during hikes.",
      "🔥 **Know how to start a fire safely** in case of emergency.",
      "🌄 **Dress in layers** to adjust to changing weather conditions while hiking.",
      "🌿 **Know the local plants and wildlife** to avoid harmful encounters.",
    ],
  },
  {
    id: "3",
    title: "Winter Sports",
    imageUrl: "https://images.unsplash.com/photo-1518775053278-5a569f0be353?q=80&w=435&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    emoji: "⛄",
    tips: [
      "🏂 **Plan activities that are suitable for all ages** in your group, from beginners to experienced.",
      "👶 **Supervise children near water** or while doing outdoor activities like skiing or ice skating.",
      "☀️ **Apply sunscreen regularly**, especially at high altitudes where the sun’s rays are stronger.",
      "❄️ **Dress in layers** to stay warm and be able to adjust to varying temperatures.",
      "🧣 **Wear a scarf, hat, and gloves** to keep extremities warm in cold weather.",
      "🥾 **Wear waterproof boots** to keep your feet dry and warm in snow.",
      "⛷️ **Take breaks to avoid exhaustion**, especially for younger children or beginners.",
      "🍫 **Carry energy snacks** like granola bars or nuts to refuel during winter activities.",
      "🚨 **Know the signs of frostbite or hypothermia**, and seek shelter immediately if symptoms occur.",
      "🔦 **Use a headlamp or flashlight** when navigating in low-light or snow-covered areas.",
    ],
  },
  {
    id: "4",
    title: "Adventure",
    imageUrl: "https://images.unsplash.com/photo-1507608443039-bfde4fbcd142?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aG90JTIwYWlyJTIwYmFsbG9vbnxlbnwwfHwwfHx8MA%3D%3D",
    emoji: "🏕️",
    tips: [
      "🎒 **Pack light but thoroughly** – bring only essential items like a multitool, first aid kit, and extra clothing.",
      "🌍 **Research your destination** – know the terrain, climate, and any potential risks or hazards.",
      "🛶 **Have a backup plan** in case of unexpected changes in weather or other conditions.",
      "🌄 **Always have a map and compass** or a fully charged GPS device, especially when exploring remote locations.",
      "🔦 **Carry a flashlight or headlamp** for visibility during night-time activities or emergencies.",
      "⚠️ **Know your physical limits** – don't take on challenges that might put your safety at risk.",
      "🗣️ **Share your itinerary** with someone trusted, in case of emergency.",
      "⏱️ **Pace yourself** and take regular breaks during long or physically demanding activities.",
      "🥾 **Choose footwear and gear** suitable for your adventure, whether it’s climbing, trekking, or kayaking.",
      "📞 **Be prepared for emergencies** – carry a satellite phone or emergency beacon in areas with no phone signal.",
    ],
  },
];
